name: deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test:ci
      - name: Build
        run: yarn build
      - name: Create artifact
        run: tar czvf dist.tar.gz dist
      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER}}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "dist.tar.gz"
          target: "~/deploy_tmp/."
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: bash deploy-server.sh

