name: run-unit-tests
on: [push]
jobs:
  rununittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test -- --coverage
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: docs
          force: true
          message: Add generated docs
        env:
          GITHUB_TOKEN: $
